import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { auth } from "config/client"
import useUser from "hooks/useUser"
import { useEffect, useState } from "react"
import { getUser } from "controllers/usersController"
import { sendEmail } from 'controllers/mailController'

export default function Home() {

  const send = async (email) => {
    await sendEmail("erikmurminacho07@outlook.com")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Music ratios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Music Ratios
        </h1>
        <button onClick={send}>Mail test</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
